version: "3"
services:
  database:
    restart: always
    image: postgis/postgis:13-master
    volumes:
      - pgd:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  web:
    command: dotnet Test.dll --environment=prod
    environment:
      ASPNETCORE_ENVIRONMENT: prod
    restart: always
    build:
      context: .
      dockerfile: Test/Dockerfile
  
  nginx:
    ports:
    - '8080:80'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  pgd:

networks:
  default:
    name: nginx
