version: "3"
services:
  web:
    command: dotnet Test.dll --environment=prod
    environment:
      ASPNETCORE_ENVIRONMENT: prod
    restart: always
    build:
      context: .
      dockerfile: Test/Dockerfile
  
  nginx:
    ports:
    - '8080:80'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

networks:
  default:
    name: nginx
